//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkraHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public string Type { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Discount { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
