//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkraHotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AkraHotelEntities : DbContext
    {
        public AkraHotelEntities()
            : base("name=AkraHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillCompany> BillCompanies { get; set; }
        public virtual DbSet<BillGuest> BillGuests { get; set; }
        public virtual DbSet<BillService> BillServices { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Complain> Complains { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomBill> RoomBills { get; set; }
        public virtual DbSet<Service> Services { get; set; }
    }
}
